services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: 'kafka'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  
  postgres:
    image: '14.4-alpine'
    ports:
      - '5432:5432'
  
  api_gateway:
    build: './API_gateway'
    container_name: api_gateway
    ports:
      - '4444:4444'
  
  users:
    build: './users'
    container_name: users
    ports:
      - '3333:3333'
    depends_on:
      - postgres
      - kafka
  
  notes:
    build: './notes'
    container_name: notes
    ports:
      - '5000:5000'
    depends_on:
      - postgres

  emails:
    build: './emails'
    container_name: emails
    ports:
      - '6666:6666'
    depends_on:
      - postgres
      - kafka